name: CI
on:
  pull_request:
env:
  RUSTFLAGS: -Dwarnings

jobs:
  check_and_test:
    name: It builds and tests pass
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: wasmcloud/setup-wash-action@main
      with:
        wash-version: 1.0.0-beta.7

    - name: Run cargo check
      shell: bash
      run: cargo check

  check_style:
    name: It follows all style conventions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wasmcloud/setup-wash-action@main
      with:
        wash-version: 1.0.0-beta.7

    - name: Run cargo clippy
      run: cargo clippy -- -Dwarnings
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
